HealthyKitchen/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HealthyKitchen.Data;

namespace HealthyKitchen.Controllers
{
    public class OrdersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrdersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Orders
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Orders.Include(o => o.User);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: Orders/Create
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,OrderedOn,Total,Finalised,UserId")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", order.UserId);
            return View(order);
        }

        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", order.UserId);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,OrderedOn,Total,Finalised,UserId")] Order order)
        {
            if (id != order.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", order.UserId);
            return View(order);
        }

        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var order = await _context.Orders.FindAsync(id);
            _context.Orders.Remove(order);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
            return _context.Orders.Any(e => e.Id == id);
        }
    }
}

HealthyKitchen/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HealthyKitchen.Data;
using HealthyKitchen.Models;

namespace HealthyKitchen.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly SignInManager<User> _signInManager;
        private readonly IWebHostEnvironment _iWebHost;

        public ProductsController(ApplicationDbContext context, SignInManager<User> signInManager, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _signInManager = signInManager;
            _iWebHost = webHostEnvironment;
        }

        public async Task<IActionResult> Index()
        {
            TempData.Keep("OrderActive");
            var applicationDbContext = _context.Products;
            return View(await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            TempData.Keep("OrderActive");

            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            ProductVM model = new ProductVM()
            {
                Id=product.Id,
                Title = product.Title,
                Description = product.Description,
                PictureFile = product.PictureFile,
                Picture = product.Picture,
                Price = product.Price,
                Quantity = product.Quantity
            };
            return View(model);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ProductVM model = new ProductVM();
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Quantity,Description,Picture,PictureFile,Price")] ProductVM product)
        {
            if (ModelState.IsValid)
            {
                string file = Path.GetFileNameWithoutExtension(product.PictureFile.FileName);
                string ext = Path.GetExtension(product.PictureFile.FileName);
                product.Picture = file + DateTime.Now.ToString("mmss") + ext;
                string path = "wwwroot/images/" + product.Picture;
                using (var fileStream = new FileStream(path, FileMode.Create))
                {
                    await product.PictureFile.CopyToAsync(fileStream);
                }

                ProductVM model = new ProductVM();
            }
            Product dbModel = new Product
            {
                Title = product.Title,
                Description = product.Description,
                PictureFile = product.PictureFile,
                Picture = product.Picture,
                Price = product.Price,
                Quantity = product.Quantity
            };
            _context.Add(dbModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ProductVM model = new ProductVM
            {
                Title = product.Title,
                Description = product.Description,
                PictureFile = product.PictureFile,
                Picture = product.Picture,
                Price = product.Price,
                Quantity = product.Quantity
            };
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Quantity,Description,PictureFile,Picture,Price")] ProductVM product, IFormFile updateImage)
        {
            Product modelToDb = await _context.Products.FindAsync(id);
            if (modelToDb == null)
            {
                return NotFound();
            }
            if (!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                _context.Products.Remove(modelToDb);
                FileInfo fileInfo = new FileInfo(product.Picture);
                if(fileInfo.Exists)
                {
                    System.IO.File.Delete(product.Picture);
                    fileInfo.Delete();
                }
                string file = Path.GetFileNameWithoutExtension(updateImage.FileName);
                string ext = Path.GetExtension(updateImage.FileName);
                product.Picture = file + DateTime.Now.ToString("mmss") + ext;
                string path = "wwwroot/images/" + product.Picture;
                using (var fileStream = new FileStream(path, FileMode.Create))
                {
                    await updateImage.CopyToAsync(fileStream);
                }
                modelToDb.Title = product.Title;
                modelToDb.Description = product.Description;
                modelToDb.PictureFile = product.PictureFile;
                modelToDb.Picture = product.Picture;
                modelToDb.Price = product.Price;
                modelToDb.Quantity = product.Quantity;
                _context.Update(modelToDb);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ProductExists(modelToDb.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction("Details", new { id = id });
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.FindAsync(id);
            _context.Products.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.Id == id);
        }
    }
}

HealthyKitchen/Views/Shared/_Layout.cshtml
@inject SignInManager<User> signInManager;
@inject UserManager<User> userInManager;
@using Microsoft.AspNetCore.Identity;
@using HealthyKitchen.Data;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Healthy Kitchen</title>
    <link asp-append-version="true" rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link asp-append-version="true" rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light box-shadow mb-3 navbar-bg">
            <div class="container">
                <a class="text-center w-20" asp-area="" asp-controller="Home" asp-action="Index">
                    <img class = "w-50" id="logo" src="~/images/logo.jpg" />
                </a>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav nav-pills flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link fs-3" asp-area="" asp-controller="Home" asp-action="Index">Начало</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link fs-3" asp-area="" asp-controller="Products" asp-action="Index">Продукти</a>
                        </li>
                        @if (signInManager.IsSignedIn(User) && User.IsInRole(Role.Admin.ToString()))
                        {
                            <li class="nav-item fs-3">
                                <a class="nav-link" asp-area="" asp-controller="Orders" asp-action="Index">Поръчки</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>


    <br />
    <br />
    <br />
    <br />

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Healthy Kitchen &nbsp;&nbsp;&nbsp; <a href="https://twitter.com/ateezofficial?lang=bg"><i class="fa-brands fa-2x fa-twitter icon-color"></i></a> &nbsp;&nbsp;&nbsp; <a href="https://www.instagram.com/ateez_official_/?hl=bg"><i class="fa-brands fa-2x fa-instagram icon-color"></i></a> &nbsp;&nbsp;&nbsp; <a href="https://open.spotify.com/artist/68KmkJeZGfwe1OUaivBa2L"><i class="fa-brands fa-2x fa-spotify icon-color"></i></a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>