HealthyKitchen/Controllers/OrderDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HealthyKitchen.Data;
using HealthyKitchen.Models;

namespace HealthyKitchen.Controllers
{
    public class OrderDetailsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<User> _userManager;
        public const string OrderSession = "OrderId";

        public OrderDetailsController(ApplicationDbContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: OrderDetails
        public async Task<IActionResult> Index()
        {
            TempData.Keep("OrderActive");

            var orderId = GetOrderId();
            if (orderId == null)
            {
                return RedirectToAction("Index", "Products");
            }
            var currentUser = _userManager.GetUserId(User);
            var applicationDbContext = _context.OrderDetails
                .Include(p => p.Product)
                .Include(o => o.Order)
                .Where(x => (x.OrderId == orderId) &&
                            (x.Order.Finalised == false) &&
                            (x.Order.UserId == currentUser)); 

            return View(await applicationDbContext.ToListAsync());
           
        }
        public async Task<IActionResult> Calculate(int orderId)
        {
            var currentUser = _userManager.GetUserId(User);
            var dbOrderList = _context.OrderDetails
               .Include(p => p.Product)
               .Include(o => o.Order)
               .Where(x => (x.OrderId == orderId) &&
                           (x.Order.Finalised == false) &&
                           (x.Order.UserId == currentUser));
            double sum = 0;
            foreach (var item in dbOrderList)
            {
                sum += (item.Product.Price * item.Quantity);
            }
            Order order = await _context.Orders.FindAsync(orderId);
            if (order == null)
            {
                return NotFound();
            }
            order.Finalised = true;
            order.Total = sum;

            _context.Orders.Update(order);
            await _context.SaveChangesAsync();
            HttpContext.Session.Remove("OrderSession");
            TempData["OrderActive"] = false;

            TempData["Message"] = "Успешно поръчахте на стойност " + sum.ToString() + "лв.";
            return RedirectToAction("Index", "Products");
        }
        [NonAction]
        public int? GetOrderId()
        {
            return HttpContext.Session.GetInt32("OrderSession");
        }

        
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductVM product)
        {
            TempData.Keep("OrderActive");

            if (!ModelState.IsValid)
            {
                ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Id");
                return View();
            }
            if (GetOrderId() == null)
            {
                Order order = new Order()
                {
                    UserId = _userManager.GetUserId(User),
                    OrderedOn = DateTime.Now
                };
                _context.Orders.Add(order);
                await _context.SaveChangesAsync();
                HttpContext.Session.SetInt32("OrderSession", order.Id);
                TempData["Message"] = "Имате поръчка, която не е завършена!";
                TempData["OrderActive"] = true;
            }

            int shopCartId = (int)GetOrderId();
            var orderItem = await _context.OrderDetails.SingleOrDefaultAsync(i => (i.ProductId == product.Id && i.OrderId == shopCartId));
            if (orderItem == null)
            {
                orderItem = new OrderDetails()
                {
                    ProductId = product.Id, 
                    Quantity = product.Quantity,
                    OrderId = (int)GetOrderId()
                };
                _context.OrderDetails.Add(orderItem);
            }
            else
            {
                orderItem.Quantity = orderItem.Quantity + product.Quantity;
                _context.OrderDetails.Update(orderItem);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Products");
        }
    }
}

HealthyKitchen/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HealthyKitchen.Data;
using HealthyKitchen.Models;

namespace HealthyKitchen.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly SignInManager<User> _signInManager;
        private readonly IWebHostEnvironment _iWebHost;

        public ProductsController(ApplicationDbContext context, SignInManager<User> signInManager, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _signInManager = signInManager;
            _iWebHost = webHostEnvironment;
        }

        public async Task<IActionResult> Index()
        {
            TempData.Keep("OrderActive");
            var applicationDbContext = _context.Products;
            return View(await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            TempData.Keep("OrderActive");

            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            ProductVM model = new ProductVM()
            {
                Id=product.Id,
                Title = product.Title,
                Description = product.Description,
                PictureFile = product.PictureFile,
                Picture = product.Picture,
                Price = product.Price,
                Quantity = product.Quantity
            };
            return View(model);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ProductVM model = new ProductVM();
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Quantity,Description,Picture,PictureFile,Price")] ProductVM product)
        {
            if (ModelState.IsValid)
            {
                string file = Path.GetFileNameWithoutExtension(product.PictureFile.FileName);
                string ext = Path.GetExtension(product.PictureFile.FileName);
                product.Picture = file + DateTime.Now.ToString("mmss") + ext;
                string path = "wwwroot/images/" + product.Picture;
                using (var fileStream = new FileStream(path, FileMode.Create))
                {
                    await product.PictureFile.CopyToAsync(fileStream);
                }

                ProductVM model = new ProductVM();
            }
            Product dbModel = new Product
            {
                Title = product.Title,
                Description = product.Description,
                PictureFile = product.PictureFile,
                Picture = product.Picture,
                Price = product.Price,
                Quantity = product.Quantity
            };
            _context.Add(dbModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ProductVM model = new ProductVM
            {
                Title = product.Title,
                Description = product.Description,
                PictureFile = product.PictureFile,
                Picture = product.Picture,
                Price = product.Price,
                Quantity = product.Quantity
            };
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Quantity,Description,PictureFile,Picture,Price")] ProductVM product, IFormFile updateImage)
        {
            Product modelToDb = await _context.Products.FindAsync(id);
            if (modelToDb == null)
            {
                return NotFound();
            }
            if (!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                _context.Products.Remove(modelToDb);
                FileInfo fileInfo = new FileInfo(product.Picture);
                if(fileInfo.Exists)
                {
                    System.IO.File.Delete(product.Picture);
                    fileInfo.Delete();
                }
                string file = Path.GetFileNameWithoutExtension(updateImage.FileName);
                string ext = Path.GetExtension(updateImage.FileName);
                product.Picture = file + DateTime.Now.ToString("mmss") + ext;
                string path = "wwwroot/images/" + product.Picture;
                using (var fileStream = new FileStream(path, FileMode.Create))
                {
                    await updateImage.CopyToAsync(fileStream);
                }
                modelToDb.Title = product.Title;
                modelToDb.Description = product.Description;
                modelToDb.PictureFile = product.PictureFile;
                modelToDb.Picture = product.Picture;
                modelToDb.Price = product.Price;
                modelToDb.Quantity = product.Quantity;
                _context.Update(modelToDb);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ProductExists(modelToDb.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction("Details", new { id = id });
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.FindAsync(id);
            _context.Products.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.Id == id);
        }
    }
}

HealthyKitchen/Views/Products/Create.cshtml
@model HealthyKitchen.Models.ProductVM

@{
    ViewData["Title"] = "Create";
}

<h1>Нов продукт</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label">Заглавие</label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Описание</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="PictureFile" class="control-label">Изображение</label>
                <input asp-for="PictureFile" accept="image/*" />
                <span asp-validation-for="PictureFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label">Цена</label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Добави" class="btn btn-success"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index"><i class="fa fa-2x fa-reply icon-color" aria-hidden="true"></i></a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HealthyKitchen/Views/Products/Delete.cshtml
@model HealthyKitchen.Data.Product

@{
    ViewData["Title"] = "Delete";
}

<h1>Изтриване</h1>

<h3>Сигурни ли сте, че искате да изтриете записа?</h3>
<div>
    <h4>Продукт</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Заглавие
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
           Описание
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            Изображение
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Picture)
        </dd>
        <dt class = "col-sm-2">
            Цена
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            Дата на добавяне
        </dt>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Изтрий" class="btn btn-danger" /> |
        <a asp-action="Index"><i class="fa fa-2x fa-reply icon-color" aria-hidden="true"></i></a>
    </form>
</div>

HealthyKitchen/Views/Products/Details.cshtml
@model HealthyKitchen.Models.ProductVM
@inject SignInManager<User> signInManager;
@inject UserManager<User> userInManager;
@using Microsoft.AspNetCore.Identity;
@using HealthyKitchen.Data;

@{ ViewData["Title"] = "Details"; }

<h1>Детайли</h1>

<form class="row" asp-controller="OrderDetails" asp-action="Create" method="post">

    <div class="col-lg-6 col-12">
        <div>
            <img class="card-img-top" src="~/images/@Html.DisplayFor(model => model.Picture)" alt="">
        </div>
    </div>

    <div class="col-lg-6 col-12">
        <div class=" d-flex">
            <div>
                <input type="hidden" asp-for="Id" />
                <input asp-for="Title" class="form-control rounded " readonly />
                <input asp-for="Price" class="form-control rounded  " readonly />
            </div>
        </div>

        <div>
            <strong class="d-block mt-4 mb-2">Описание</strong>
            <input asp-for="Description" class="form-control rounded " readonly />
        </div>
        <label asp-for="Quantity" class="control-label">Количество</label>
        <input asp-for="Quantity" type="number" maxlength="4" class="form-control rounded " />
        <span asp-validation-for="Quantity" class="text-danger"></span>
        @if (User.Identity.IsAuthenticated)
        {
            <br />
            <br />
            <input type="submit" class="btn btn-success" value="Добави в кошницата" &nbsp;&nbsp;&nbsp; /> 	
            <a class="btn btn-success" value="Finalise" asp-controller="OrderDetails" asp-action="Index">Поръчай</a>
         }
    </div>
</form>


<div>
    @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
     {
        <a asp-action="Edit" asp-route-id="@Model.Id"><i class="fa fa-2x fa-pencil icon-color" aria-hidden="true"></i></a>
        <a asp-action="Delete" asp-route-id="@Model.Id"><i class="fa fa-2x fa-trash icon-color" aria-hidden="true"></i></a>
     }
    <a asp-action="Index"><i class="fa fa-2x fa-reply icon-color" aria-hidden="true"></i></a>
</div>

HealthyKitchen/Views/Products/Edit.cshtml
@model HealthyKitchen.Models.ProductVM

@{
    ViewData["Title"] = "Edit";
}

<h1>Редактиране</h1>

<h4>Продукт</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label">Заглавие</label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Описание</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="PictureFile" />
                <img src="@("/images/" + Model.Picture)" />

                <label>Изображение</label>
                <input type="file" name="updateImage"/>
            </div>
            <div class="form-group">
                <label asp-for="Picture" class="control-label">Изображение</label>
                <input asp-for="Picture" class="form-control" readonly/>
                <span asp-validation-for="Picture" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label">Цена</label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Запази" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index"><i class="fa fa-2x fa-reply icon-color" aria-hidden="true"></i></a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HealthyKitchen/Views/Products/Index.cshtml
@model IEnumerable<HealthyKitchen.Data.Product>
@inject SignInManager<User> signInManager;
@inject UserManager<User> userInManager;
@using HealthyKitchen.Data;
@using Microsoft.AspNetCore.Identity;
@{ ViewData["Title"] = "Index"; }

<h1>Продукти</h1>
@{bool flag = (bool)TempData["OrderActive"];
    if (flag)
    {
        <a class="nav-link" asp-controller="OrderDetails" asp-action="Index"><i class="fa fa-2x fa-shopping-bag icon-color" aria-hidden="true"></i></a>
    }
}

@if (signInManager.IsSignedIn(User) && User.IsInRole(Role.Admin.ToString()))
{
<p>
    <a asp-action="Create"><i class="fa fa-2x fa-plus-square icon-color" aria-hidden="true"></i></a>
</p>
<br />
}

<div class="alert-success"> @TempData["Message"]</div>

<br />
<div class="container">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-md-4 mb-4 mx-auto">
                <div class="card">
                    <img class="card-img-top" src="~/images/@item.Picture" alt="Card image">
                    <div class="card-body">
                        <h5 class="card-title">
                            <a asp-action="Details" asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.Title)</a>
                        </h5>
                        <p class="card-text">@Html.DisplayFor(modelItem => item.Price) лв.</p>
                    </div>
                </div>
            </div>
        }
    </div>
</div>